### ISSUE TITLE
Version 0.5 Roadmap

### ISSUE THREAD

**Issue by edward-ly** [edward-ly/stepmania-song-manager#14]
Planned features for the 0.5 release which is no longer in development:

- [ ] dark mode support
- [ ] display progress bar and real-time status when downloading content
- [ ] support for additional languages
- [ ] embed donate button in About section
